#!/bin/sh

#
# Copyright © 2015-2021 the original authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

##############################################################################
#
#   Gradle start up script for POSIX generated by Gradle.
#
#   Important for running:
#
#   (1) You need a POSIX-compliant shell to run this script. If your /bin/sh is
#       noncompliant, but you have some other compliant shell such as ksh or
#       bash, then run this script invoking that shell by setting the SHELL
#       environment variable to point to it before running this script:
#           SHELL=/usr/bin/ksh ./gradlew
#
#       In addition, exporting the SHELL environment variable may be required
#       for Cygwin/MSYS2, which have noncompliant shells by default. You can
#       set the SHELL environment variable by adding the following to your
#       ~/.bashrc or ~/.profile:
#           export SHELL=/usr/bin/bash
#
#   (2) The path to this script must not have spaces in it. The path to the
#       Java installation must not have spaces in it.
#
#   (3) Some distributions (like MacOS) use the '+' character as a special
#       character for filename expansion; ensure that the path to this script
#       does not contain the '+' character.
#
##############################################################################

# Attempt to set APP_HOME

# Resolve links: $0 may be a link
app_path=$0

# Need this for daisy-chained symlinks.
while
    APP_HOME=${app_path%"${app_path##*/}"}  # leaves a trailing /; empty if no leading path
    [ -h "$app_path" ]
do
    ls=$(ls -ld "$app_path")
    link=${ls#*' -> '}
    case $link in             #(
      /*)   app_path=$link ;; #(
      *)    app_path=$APP_HOME$link ;;
    esac
done

# This is normally unused
# shellcheck disable=SC2034
APP_BASE_NAME=${0##*/}
APP_HOME=$( cd "${APP_HOME:-./}" && pwd -P ) || exit

# Use the maximum available, or set MAX_FD != -1 to use that value.
MAX_FD=maximum

warn () {
    echo "$*"
} >&2

die () {
    echo
    echo "$*"
    echo
    exit 1
} >&2

# OS specific support (must be 'true' or 'false').
cygwin=false
msys=false
darwin=false
nonstop=false
case "$( uname )" in                #(
  CYGWIN* )         cygwin=true  ;; #(
  Darwin* )         darwin=true  ;; #(
  MSYS* | MINGW* )  msys=true    ;; #(
  NONSTOP* )        nonstop=true ;;
esac

CLASSPATH=$APP_HOME/gradle/wrapper/gradle-wrapper.jar

# Determine the Java command to use to start the JVM.
if [ -n "$JAVA_HOME" ] ; then
    if [ -x "$JAVA_HOME/jre/sh/java" ] ; then
        # IBM's JDK on AIX uses strange locations for the executables
        JAVACMD=$JAVA_HOME/jre/sh/java
    else
        JAVACMD=$JAVA_HOME/bin/java
    fi
    if [ ! -x "$JAVACMD" ] ; then
        die "ERROR: JAVA_HOME is set to an invalid directory: $JAVA_HOME

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
else
    JAVACMD=java
    if ! command -v java >/dev/null 2>&1
    then
        die "ERROR: JAVA_HOME is not set and no 'java' command could be found in your PATH.

Please set the JAVA_HOME variable in your environment to match the
location of your Java installation."
    fi
fi

# Increase the maximum file descriptors if we can.
if ! "$cygwin" && ! "$darwin" && ! "$nonstop" ; then
    case $MAX_FD in #(
      max*)
        # In POSIX sh, ulimit -H is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        MAX_FD=$( ulimit -H -n ) ||
            warn "Could not query maximum file descriptor limit"
    esac
    case $MAX_FD in  #(
      '' | soft) :;; #(
      *)
        # In POSIX sh, ulimit -n is undefined. That's why the result is checked to see if it worked.
        # shellcheck disable=SC3045
        ulimit -n "$MAX_FD" ||
            warn "Could not set maximum file descriptor limit to $MAX_FD"
    esac
fi

# Collect all arguments for the java command, stacking in reverse order:
#   * args from the command line
#   * the main class name
#   * -classpath
#   * -D...appname settings
#   * --module-path (only if needed)
#   * DEFAULT_JVM_OPTS, JAVA_OPTS, and GRADLE_OPTS environment variables.

# For Cygwin or MSYS, switch paths to Windows format before running java
if "$cygwin" || "$msys" ; then
    APP_HOME=$( cygpath --path --mixed "$APP_HOME" )
    CLASSPATH=$( cygpath --path --mixed "$CLASSPATH" )

    JAVACMD=$( cygpath --unix "$JAVACMD" )

    # Now convert the arguments - kludge to limit ourselves to /bin/sh
    for arg do
        if
            case $arg in                                #(
              -*)   false ;;                            # don't mess with options #(
              /?*)  t=${arg#/} t=/${t%%/*}              # looks like a POSIX filepath
                    [ -e "$t" ] ;;                      #(
              *)    false ;;
            esac
        then
            arg=$( cygpath --path --ignore --mixed "$arg" )
        fi
        # Roll the args list around exactly as many times as the number of
        # args, so each arg winds up back in the position where it started, but
        # possibly modified.
        #
        # NB: a `for` loop captures its iteration list before it begins, so
        # changing the positional parameters below affects the iteration
        # list, but not the arguments in the list, so this is safe.
        set -- "$@" "$arg"
    done
fi

# Collect all arguments for the java command;
#   * $DEFAULT_JVM_OPTS, $JAVA_OPTS, and $GRADLE_OPTS can contain fragments of
#     shell script including quotes and variable substitutions, so put them in
#     double quotes to make sure that they get re-expanded; and
#   * put everything else in single quotes, so that it's not re-expanded.

set -- \
        "-Dorg.gradle.appname=$APP_BASE_NAME" \
        -classpath "$CLASSPATH" \
        org.gradle.wrapper.GradleWrapperMain \
        "$@"

# Stop when "xargs" is not available.
if ! command -v xargs >/dev/null 2>&1
then
    die "xargs is not available"
fi

# Use "xargs" to parse quoted args.
#
# With -n1 it outputs one arg per line, with the quotes and backslashes removed.
#
# In Bash we could simply go:
#
#   readarray ARGS < <( xargs -n1 <<<"$var" ) &&
#   set -- "${ARGS[@]}" "$@"
#
# but POSIX shell has neither arrays nor command substitution, so instead we
# post-process each arg (as a line of input to sed) to backslash-escape any
# character that might be a shell metacharacter, then use `xargs` to gather
# the arguments into one safe set, and then re-import them into the
# positional parameters.

# The following line is a trick to extract the first character from $@
# as a way of checking if there are any arguments.
# (There is no way to check for $@ in POSIX shell without iterating until
# it's exhausted, but the first arg is good enough for our purposes.)
first_arg=$1
if [ -z "$first_arg" ]; then
    # If there are no arguments, we need to ensure that the variable is set
    # to an empty string, otherwise the xargs line below will interpret it
    # as an argument to xargs itself.
    set -- ""
fi

# Split the arguments into an array, using newline as the delimiter, but
# only if there is at least one argument.
if [ "$#" -gt 0 ]; then
    # Quotes are not needed for xargs because we are passing the arguments
    # as a single string to xargs, and xargs will split them.
    # xargs will also remove the quotes, so we need to re-add them.
    # We use xargs with -n1 to split the arguments into separate lines,
    # then we recombine them with quotes using sed.
    # We use `printf '%s\n'` to ensure that the arguments are printed
    # with newline separation.
    printf '%s\n' "$@" | \
    xargs -n1 | \
    sed 's/[]"$&\\()*?;|]/\\&/g' | \
    xargs printf '"%s" ' | \
    xargs printf "%s" > /tmp/gradle_args_$$.txt

    # Now read the arguments back from the file
    set -- $(cat /tmp/gradle_args_$$.txt)
    rm /tmp/gradle_args_$$.txt
fi

# Use "xargs" to parse the arguments from the positional parameters.
# This will recombine the arguments into a single string, then split them
# again using xargs, and finally quote them for safe use.
# We use `printf '%s\n'` to ensure that the arguments are printed
# with newline separation, and then we pipe them through xargs to split
# them, and then through sed to quote them.
printf '%s\n' "$@" | \
xargs -n1 | \
sed 's/[]"$&\\()*?;|]/\\&/g' | \
xargs printf '"%s" ' | \
xargs printf "%s" > /tmp/gradle_args_$$.txt

# Now read the arguments back from the file
set -- $(cat /tmp/gradle_args_$$.txt)
rm /tmp/gradle_args_$$.txt

# Collect the arguments into a single string to pass to the Java command.
# We need to quote each argument to preserve spaces.
args=""
for arg do
    args="$args \"$arg\""
done

# Print the final command for debugging if needed
# echo "Executing: $JAVACMD $args"

# Execute the Java command.
exec $JAVACMD $args
